version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

dist: xenial

language: scala

script:
  - sbt "+test" "publishLocal; toShade/publishLocal ;scripted"

env: ADOPTOPENJDK=11

matrix:
  include:
  - env: ADOPTOPENJDK=8
  - env: ADOPTOPENJDK=11
